# Rails
alias be="bundle exec"
alias bec="bundle exec rails c"
alias ber="bundle exec rails s"
alias s="spring"
alias precompile="bundle exec rake assets:precompile"
alias bem="bundle exec rake db:migrate"
alias wpd="bin/webpack-dev-server"

# Git
alias g="git"

# Docker
alias dc="docker-compose"
alias k="kubectl"

# JS
alias cy="yarn cy:open"

# Utility
alias hg='history | grep'

kill_port() {
  if [ -n "$1" ]
  then
    lsof -ti :"$1" | xargs kill -9
  else
    echo "Pass in port number."
  fi
}

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ngaicojal"

plugins=(asdf git ruby)

source $ZSH/oh-my-zsh.sh
export EDITOR="vim"
export PATH="/usr/local/bin:$PATH"
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
. /usr/local/opt/asdf/libexec/asdf.sh
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
